version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:latest

    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet build


workflows:
  version: 2
  build:
    jobs:
      - build
