version: 2.1
orbs:
  dotnet: circleci/dotnet@4.1.0
jobs:
  build:
    executor: dotnet/default
    steps:
      - dotnet restore
      - dotnet build
  
workflows:
  build:
    jobs:
      - build
    

