version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:6.0

    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the .NET application
      - run:
          name: Build Application
          command: dotnet build --configuration Release

workflows:
  version: 2
  build:
    jobs:
      - build
